services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-6.4.14
    container_name: zabbix-server
    hostname: zabbix-server
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
      - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - snmptraps:/var/lib/zabbix/snmptraps:rw
      - ./certificates/ca-cert.pem:/certificates/ca-cert.pem
      - ./certificates/zabbix-agent-cert.pem:/certificates/zabbix-agent-cert.pem
      - ./certificates/zabbix-agent-key.pem:/certificates/zabbix-agent-key.pem
    #   - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
    #   - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
    #   - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    # deploy:
      #resources:
      #  limits:
      #    cpus: '0.70'
      #    memory: 1G
      #  reservations:
      #    cpus: '0.5'
      #    memory: 512M
    env_file:
      - ./env_vars/.env_db_pgsql
      - ./env_vars/.env_srv
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      - postgres-server
      - dnsmasq
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-server
          - zabbix-server-pgsql
          - zabbix-server-ubuntu-pgsql
          - zabbix-server-pgsql-ubuntu
      zbx_net_frontend:
        # ipv4_address is static because in zabbix-agent on this host
        # should be manual configured zabbix-server ip
        ipv4_address: 172.16.238.3

    #  devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    dns:
      - 172.16.239.10
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 64999
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    labels:
      com.zabbix.description: "Zabbix server with PostgreSQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "pgsql"
      com.zabbix.os: "ubuntu"
    restart: unless-stopped

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-6.4-latest
    container_name: zabbix-web
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
      - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    #   - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
    #   - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
    #   - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.70'
    #      memory: 512M
    #    reservations:
    #      cpus: '0.5'
    #      memory: 256M
    env_file:
      - ./env_vars/.env_db_pgsql
      - ./env_vars/.env_web
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      - postgres-server
      - zabbix-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-web-nginx-pgsql
          - zabbix-web-nginx-ubuntu-pgsql
          - zabbix-web-nginx-pgsql-ubuntu
      zbx_net_frontend:
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    labels:
      com.zabbix.description: "Zabbix frontend on Nginx web-server with PostgreSQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.webserver: "nginx"
      com.zabbix.dbtype: "pgsql"
      com.zabbix.os: "ubuntu"
    restart: unless-stopped

  postgres-server:
    image: postgres:15-alpine
    #  command: -c ssl=on -c ssl_cert_file=/run/secrets/server-cert.pem -c ssl_key_file=/run/secrets/server-key.pem -c ssl_ca_file=/run/secrets/root-ca.pem
    volumes:
      - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw
      - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
      - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
      - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
    env_file:
      - ./env_vars/.env_db_pgsql
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    stop_grace_period: 1m
    networks:
      zbx_net_backend:
        aliases:
          - postgres-server
          - pgsql-server
          - pgsql-database
    restart: unless-stopped


  db_data_pgsql:
    image: busybox
    volumes:
      - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw

  postgres-backups-fix-volumes-permissions:
    image: prodrigestivill/postgres-backup-local
    volumes:
      - ./.backups:/backups
    user: root
    entrypoint: []
    # TODO Make more secure then 777
    command: /bin/sh -c "chmod 777 /backups"


  postgres-backups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres # Optional: see below
    volumes:
      - ./.backups:/backups
    networks:
      zbx_net_backend:
    depends_on:
      - postgres-backups-fix-volumes-permissions
      - postgres-server
    environment:
      - POSTGRES_HOST=postgres-server
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      #  - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      # - SCHEDULE=@daily
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080

  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    networks:
      zbx_net_backend:
        ipv4_address: 172.16.239.10
      zbx_net_frontend:
    command:
      # Docs: https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html
      - --keep-in-foreground
      - --cache-size=10000
      - --proxy-dnssec
      - --log-facility=-
      - --strict-order
      - --conf-file=-
    restart: unless-stopped

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24

volumes:
  snmptraps:

secrets:
  MYSQL_USER:
    file: ./env_vars/.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./env_vars/.MYSQL_PASSWORD
  MYSQL_ROOT_USER:
    file: ./env_vars/.MYSQL_ROOT_USER
  MYSQL_ROOT_PASSWORD:
    file: ./env_vars/.MYSQL_ROOT_PASSWORD
  POSTGRES_USER:
    file: ./env_vars/.POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./env_vars/.POSTGRES_PASSWORD
